account/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.urls.conf import path
from . import views

app_name = 'account'
urlpatterns = [
    path('login/', views.cmdb_login, name="login"),
    path('logout/', views.cmdb_logout, name="logout"),
    path('my-page/', views.my_page, name="my-page"),
    path('manager/', views.user_manager, name="manager"),
    path('add/', views.add_user, name="add"),
    path('', views.test, name="test"),
]

home/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
]

yy_cmdb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('cmdb_admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('asset/', include('asset.urls', namespace='asset')),
    path('manyhand/', include('manyhand.urls', namespace='manyhand')),
    path('', include('home.urls', namespace='index')),
]

templates/base/index.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
    <title>友游CMDB | {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
          integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/spur.css' %}">

    {% block style %}{% endblock %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body>
<div class="dash">
    <div class="dash-nav dash-nav-dark">
        <header>
            <a href="{% url 'home:index' %}" class="spur-logo"><i class="fas fa-dragon"></i> <span>YY CMDB</span></a>
        </header>
        <nav class="dash-nav-list">
            <a href="{% url 'home:index' %}" class="dash-nav-item">
                <i class="fas fa-home"></i> Dashboard </a>
            <a href="{% url 'asset:index' %}" class="dash-nav-item">
                <i class="fas fa-server"></i> 资产管理 </a>
            <a href="{% url 'manyhand:index' %}" class="dash-nav-item">
                <i class="fas fa-tasks"></i> 批量执行 </a>
            <a href="#!" class="dash-nav-item">
                <i class="fas fa-desktop"></i> 终端界面 </a>
            <a href="{% url 'account:manager' %}" class="dash-nav-item">
                <i class="fas fa-user-tie"></i> 用户管理 </a>
        </nav>
    </div>
    <div class="dash-app">
        <header class="dash-toolbar">
            <div class="tools">
                <a href="#" target="_blank" class="tools-item">
                    <i class="fab fa-github"></i>
                </a>
                <a href="#" class="tools-item">
                    <i class="fas fa-bell"></i>
                    <i class="tools-item-count">4</i>
                </a>
                <div class="dropdown tools-item">
                    <a href="#" class="" id="dropdownUserMenu" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false">
                        <i class="fas fa-user"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownUserMenu">
                        <a class="dropdown-item" href="{% url 'account:my-page' %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
                    </div>
                </div>
            </div>
        </header>
        <main class="dash-content">
            <div class="container-fluid">
                {% block content %}{% endblock %}
            </div>
        </main>

    </div>
</div>

</body>
<script src="{% static 'js/jquery.3.2.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block js %}

{% endblock %}
</html>