asset/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.urls import path
from . import views

app_name = 'asset'
urlpatterns = [
    path('update/', views.update, name='update'),
    path('', views.index, name='index')
]

home/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
]

yy_cmdb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('cmdb_admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('asset/', include('asset.urls', namespace='asset')),
    path('manyhand/', include('manyhand.urls', namespace='manyhand')),
    path('', include('home.urls', namespace='index')),
]

asset/models.py
from django.db import models


class Asset(models.Model):
    host_name = models.CharField(max_length=50, blank=False, null=False, unique=True)
    host_group = models.CharField(max_length=20, blank=True, null=True)
    internal_ip = models.GenericIPAddressField(protocol='ipv4', max_length=20, blank=False, null=False, unique=True)
    external_ip = models.GenericIPAddressField(protocol='ipv4', max_length=20, unique=True, blank=True, null=True)
    host_cpu = models.SmallIntegerField(blank=False, null=False)
    host_memory = models.SmallIntegerField(blank=False, null=False)

    def __str__(self):
        return self.host_name

asset/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms
from .models import Asset


class AssetForm(forms.ModelForm):
    host_name = forms.CharField(
        label='主机名',
        widget=forms.TextInput(
            attrs={
                'placeholder': '主机名',
                'class': 'form-control'
            }
        )
    )
    # host_group = forms.ChoiceField(
    #     label='主机组',
    #     widget=forms.Select(
    #         attrs={
    #             'class': 'form-control'
    #         }
    #     )
    # )
    host_group = forms.CharField(
        label='主机组',
        widget=forms.TextInput(
            attrs={
                'placeholder': '主机组',
                'class': 'form-control'
            }
        )
    )
    internal_ip = forms.GenericIPAddressField(
        label='内网IP',
        widget=forms.TextInput(
            attrs={
                'placeholder': '内网IP',
                'class': 'form-control'
            }
        )
    )
    external_ip = forms.GenericIPAddressField(
        label='外网IP',
        widget=forms.TextInput(
            attrs={
                'placeholder': '外网IP',
                'class': 'form-control'
            }
        )
    )
    host_cpu = forms.IntegerField(
        label='CPU',
        widget=forms.NumberInput(
            attrs={
                'placeholder': 'CPU',
                'class': 'form-control'
            }
        )
    )
    host_memory = forms.IntegerField(
        label='内存',
        widget=forms.NumberInput(
            attrs={
                'placeholder': '内存',
                'class': 'form-control',
            }
        )
    )

    # def __init__(self, *args, **kwargs):
    #     super(AssetForm, self).__init__(*args, **kwargs)
    #     print(Asset.objects.values_list('host_group'))
    #     self.fields['host_group'].choices = Asset.objects.values_list('id', 'host_group')

    def __init__(self, *args, **kwargs):
        super(AssetForm, self).__init__(*args, **kwargs)
        self.fields['host_group'].required = False
        self.fields['external_ip'].required = False

    class Meta:
        model = Asset
        fields = "__all__"
        error_messages = {
            'host_name': {
                'required': '此处不能为空'
            },
            'internal_ip': {
                'required': '此处不能为空',
                'invalid': '请输入一个有效的IP地址'
            },
            'host_memory': {
                'required': '此处不能为空',
                'invalid': '请输入一个有效的数字'
            },
            'host_cpu': {
                'required': '此处不能为空',
                'invalid': '请输入一个有效的数字'
            },
            'external_ip': {
                'invalid': '请输入一个有效的IP地址'
            },
        }

asset/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from .models import Asset
from .forms import AssetForm
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    if request.method == 'GET':
        id = request.GET.get('id', '')
        if id:
            Asset.objects.get(pk=id).delete()
            return HttpResponse("ok")

    form = AssetForm(request.POST or None)

    if form.is_valid():
        asset = form.save(commit=False)
        asset.host_group = request.POST.get('host_group', '')
        asset.internal_ip = request.POST.get('internal_ip')
        asset.external_ip = request.POST.get('external_ip', '')
        asset.host_memory = request.POST.get('host_memory')
        asset.host_cpu = request.POST.get('host_cpu')
        asset.save()
    asset_list = Asset.objects.all()
    context = {'form': form, 'asset_list': asset_list, 'current_user': request.user}
    return render(request, 'asset/index.html', context)


@login_required
def update(request):
    if request.method == 'POST':
        host_name = request.POST.get('host_name')
        asset = Asset.objects.get(host_name=host_name)
        asset.host_group = request.POST.get('host_group', '')
        asset.internal_ip = request.POST.get('internal_ip')
        if request.POST.get('external_ip', '') == str('None'):
            asset.external_ip = ''
        else:
            asset.external_ip = request.POST.get('external_ip')
        asset.host_memory = request.POST.get('host_memory')
        asset.host_cpu = request.POST.get('host_cpu')

        asset.save()
    return redirect('asset:index')

templates/asset/add_form.html
{% for filed in form %}
    <div class="form-group">
        <label>{{ filed.label }}</label>
        {{ filed }}
    </div>
{% endfor %}
<div class="form-group">
    {{ form.errors }}
</div>

<button type="submit" class="btn btn-primary">保存</button>

templates/asset/index.html
{% extends 'base/index.html' %}
{% load static %}

{% block title %}
    资产管理
{% endblock %}

{% block content %}
    <main class="dash-content">
        <div class="row">
            <div class="col-xl-12">
                <div class="card spur-card">
                    <div class="card-header">
                        <div class="spur-card-icon">
                            <i class="fas fa-list-alt"></i>
                        </div>
                        <div class="spur-card-title">资产列表</div>
                        <div class="spur-card-menu">
                            <button class="btn btn-primary" data-toggle="modal"
                                    data-target="#addModal">
                                添加
                            </button>

                            <div class="modal fade" id="addModal" tabindex="-1"
                                 role="dialog" aria-labelledby="addModalLabel"
                                 aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="addModalLabel">添加资产</h5>
                                            <button type="button" class="close" data-dismiss="modal"
                                                    aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <form class="form-group" method="post"
                                                  action="{% url 'asset:index' %}" novalidate>
                                                {% csrf_token %}
                                                {% include 'asset/add_form.html' %}
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body ">
                        <div class="row bg-light mb-3">
                            <div class="col-2 p-2">主机名</div>
                            <div class="col-2 p-2">主机组</div>
                            <div class="col-2 p-2">内网IP</div>
                            <div class="col-2 p-2">外网IP</div>
                            <div class="col-1 p-2">CPU</div>
                            <div class="col-1 p-2">内存</div>
                        </div>
                        {% for asset in asset_list %}
                            <div class="row bg-light mb-3">
                                <div class="col-2 p-2">{{ asset.host_name }}</div>
                                {% if asset.host_group %}
                                    <div class="col-2 p-2">{{ asset.host_group }}</div>
                                {% else %}
                                    <div class="col-2 p-2">无</div>
                                {% endif %}
                                <div class="col-2 p-2">{{ asset.internal_ip }}</div>
                                {% if asset.external_ip %}
                                    <div class="col-2 p-2">{{ asset.external_ip }}</div>
                                {% else %}
                                    <div class="col-2 p-2">无</div>
                                {% endif %}
                                <div class="col-1 p-2">{{ asset.host_cpu }}</div>
                                <div class="col-1 p-2">{{ asset.host_memory }}</div>

                                {% if current_user.is_superuser %}
                                    <div class="col-2 p-2">
                                        <button class="btn btn-primary" data-toggle="modal"
                                                data-target="#updateModal{{ asset.id }}">
                                            修改
                                        </button>

                                        <div class="modal fade" id="updateModal{{ asset.id }}" tabindex="-1"
                                             role="dialog"
                                             aria-labelledby="updateModal{{ asset.id }}lLabel" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="updateModal{{ asset.id }}Label">
                                                            修改{{ asset.host_name }}</h5>
                                                        <button type="button" class="close" data-dismiss="modal"
                                                                aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <form class="form-group" method="post"
                                                              action="{% url 'asset:update' %}"
                                                              novalidate>
                                                            {% csrf_token %}
                                                            <div class="form-group">
                                                                <label>主机名</label>
                                                                <input type="text" name="host_name" placeholder="主机名"
                                                                       class="form-control"
                                                                       value="{{ asset.host_name }}"
                                                                       id="id_host_name" readonly>
                                                            </div>

                                                            <div class="form-group">
                                                                <label>主机组</label>
                                                                <input type="text" name="host_group" placeholder="主机组"
                                                                       class="form-control" id="id_host_group"
                                                                       value="{{ asset.host_group }}">
                                                            </div>

                                                            <div class="form-group">
                                                                <label>内网IP</label>
                                                                <input type="text" name="internal_ip" placeholder="内网IP"
                                                                       class="form-control" required=""
                                                                       id="id_internal_ip"
                                                                       value="{{ asset.internal_ip }}">
                                                            </div>

                                                            <div class="form-group">
                                                                <label>外网IP</label>
                                                                <input type="text" name="external_ip" placeholder="外网IP"
                                                                       class="form-control" id="id_external_ip"
                                                                       value="{{ asset.external_ip }}">
                                                            </div>

                                                            <div class="form-group">
                                                                <label>CPU</label>
                                                                <input type="number" name="host_cpu" placeholder="CPU"
                                                                       class="form-control" required=""
                                                                       id="id_host_cpu" value="{{ asset.host_cpu }}">
                                                            </div>

                                                            <div class="form-group">
                                                                <label>内存</label>
                                                                <input type="number" name="host_memory" placeholder="内存"
                                                                       class="form-control" required=""
                                                                       id="id_host_memory"
                                                                       value="{{ asset.host_memory }}">
                                                            </div>
                                                            {% if form.errors %}
                                                                <div class="form-group">
                                                                    <small>{{ form.errors }}</small>
                                                                </div>
                                                            {% endif %}
                                                            <button type="submit" class="btn btn-primary">保存</button>

                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <button class="btn btn-danger delete_asset" type="button"
                                                value="{{ asset.id }}">删除
                                        </button>
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

{% block js %}
    <script>
        $('.delete_asset').click(function () {
            var id = $(this).val();
            $.ajax({
                type: "GET",
                url: "/asset/",
                data: {'id': id},
                success: function (data) {
                    if (data === 'ok') {
                        window.location.reload()
                    }
                }
            })
        })
    </script>
{% endblock %}